services:
  - type: web
    name: real-time-collaboration-editor-backend
    rootDir: ./
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: PORT
        value: "10000"
